### ISSUE TITLE
`selectedNodes` not updated after node deletion

### ISSUE THREAD

**Issue by l3bioinfo** [the-grid/the-graph#195]
Steps to reproduce:
1. Visit http://the-grid.github.io/the-graph/the-graph-editor/index.html
2. Select a node
3. In developer console, run `document.getElementById('editor').selectedNodes`
4. Delete the selected node
5. Run `document.getElementById('editor').selectedNodes` again and see the deleted node still exist in the selectedNodes aray

**Comment by bergie** [comment]
Thanks for reporting! This is indeed annoying, as noflo-ui may be left with lingering node inspectors when this happens.

**Comment by forresto** [comment]
(Also fixed for edges.)

**Comment by lacek** [comment]
I think the same problem applies to `errorNodes` too.
