### ISSUE TITLE
KLayJS output  JSON as input to the-graph api to visualize graph

### ISSUE THREAD

**Issue by jambazzcoder** [the-grid/the-graph#198]
Is it possible to feed output from https://github.com/noflo/klayjs-noflo to the-graph api to visualize the actual graph?

**Comment by forresto** [comment]
Not sure what the question is, but that library is integrated: https://github.com/the-grid/the-graph/blob/master/the-graph/the-graph.html#L213

See example: http://the-grid.github.io/the-graph/the-graph-editor/index.html

**Comment by forresto** [comment]
Did this answer your question?
