### ISSUE TITLE
horizontal lay out a graph

### ISSUE THREAD

**Issue by jambazzcoder** [the-grid/the-graph#200]
![graph-vert](https://cloud.githubusercontent.com/assets/3013594/6245874/037df198-b789-11e4-8f4c-4ed61dd42402.jpg)

How to align above graph horizontally ? I am using json file for data.
The graph was automatically lay outed after rendering.

graph json:

loadGraph({
  "id": "ti6yn",
  "project": "",  
"properties": {
    "name": "photobooth",
    "environment": {
      "runtime": "html",
      "src": "preview/iframe.html",
      "width": 300,
      "height": 300    
    }
  },
  "groups": [    
    {
      "name": "Linux Server",
      "nodes": ["1", "2", "3", "4","5","6","7","8"],
      "metadata": {
        "description": "",
        "color": 2
      }
    }
  ],
  "processes": {
    "1": {    
      "metadata": {        
        "label": "Linux OS"
      }
    },
    "2": {    
      "metadata": {
        "label": "SNMP and HP SNMP Agents"
      }
    },
	"3": {    
      "metadata": {
        "label": "Logrotate"
      }
    },
	"4": {    
      "metadata": {
        "label": "Network and Routing"
      }
    },
	"5": {    
      "metadata": {
        "label": "NTP"
      }
    },
	"6": {    
      "metadata": {
        "label": "vncserver"
      }
    },
	"7": {    
      "metadata": {
        "label": "SSH"
      }
    },
	"8": {    
      "metadata": {
        "label": "Syslog"
      }
    }
  },
  "connections": [ ]
});

**Comment by forresto** [comment]
If there are no connections, this is how the layout algorithm is designed to work. If you want to manually / programmatically lay them out, set the process.metadata.x/y
