### ISSUE TITLE
Make the-graph-editor easier to embed by having it fire events when its graph changes

### ISSUE THREAD

**Issue by townxelliot** [the-grid/the-graph#203]
the-graph-editor has a `graph` and `nofloGraph` properties which are not initialised until `graph` is set to some value (at which point the initial library is loaded etc. and `nofloGraph` references a NoFlo Graph instance).

This makes it difficult to embed/test the-graph-editor, as there is no way to hook listeners to it to find out when initialisation has taken place. It's also not possible for elements which embed the-graph-editor to add event listeners to `graph` or `nofloGraph` until they are initialised, as they are null when the-graph-editor is created.

My suggestion would be to have the-graph-editor fire a `graphChanged` event when its own graph changes (and possibly a `graphInitialised` event the first time `nofloGraph` is set). That way, elements embedding the-graph-editor could listen for those events so they know when nodes/edges can be added to the graph.

I can provide a patch if it's agreed that it would be useful.

**Comment by forresto** [comment]
Internally, the-graph-editor [listens to noflo graph](https://github.com/the-grid/the-graph/blob/6c24c553c08b2415e18e691fc4a57f94fef62ab0/the-graph/the-graph-graph.js#L102-L116) change events. So maybe that's better as a single source of truth?

Patch for `graphInitialised` would be welcome if it is helpful.
