### ISSUE TITLE
Any reason why the-graph-thumb can't redraw unless the graph has edges?

### ISSUE THREAD

**Issue by townxelliot** [the-grid/the-graph#212]
In the-graph-thumb.html, `redrawGraph()` method, there's a guard to prevent a redraw unless the graph has edges:

```
        if (!this.graph || !this.graph.edges.length) {
          return;
        }
```

Is there any reason for this? It makes sense to me to redraw even if there are no edges. Otherwise, clearing the graph results in the thumb being stale, as it's not redrawn for the new empty graph.

Removing the second part of the conditional provides better behaviour, as the thumb will correctly be cleared if the graph is reset or all of its edges removed.

**Comment by forresto** [comment]
I can't see a good reason for it.
