### ISSUE TITLE
how to create a 'component library' / ports?

### ISSUE THREAD

**Issue by freder** [the-grid/the-graph#216]
hi,

I'm trying to use `the-graph` as a graph editor / visualization component for s.th. non-`noflo`-related, and I have some general questions:

__0. is this project supposed to be used like that, or is it specifically targeted at `noflo`?__

__1. do you plan to make `the-graph` installable via `npm` or `bower`?__

---

I already figured out how to programmatically create `noflo.Graph`s, or load them as JSON:

![screen shot 2015-06-12 at 16 49 27](https://cloud.githubusercontent.com/assets/724844/8133025/e60e2762-1125-11e5-9f7e-c6c71080df10.png)

but the other thing I haven't found out yet, is

__2. how do you specify which in/outports a node has without making `connections`?__

apparently [for the `Graph` itself you can do it](https://github.com/the-grid/the-graph/blob/master/the-graph-editor/photobooth.json.js#L14-L37), but what about the `processes`?

I saw there is [a "component library" in demo-simple.html](https://github.com/the-grid/the-graph/blob/master/the-graph-editor/demo-simple.html#L103-L117), so I tried this, but without success:

```javascript
loadGraph({
    "properties": {},
    "inports": {},
    "outports": {},
    "groups": [
        // ...
    ],
    "processes": {
        // ...
    },
    "connections": [{
        // ...
    }],

    // this doesn't work:
    library: {
        /*
        .
        .
        .
        */
    }
});
```

---

thanks for `the-graph`, and for your help in advance.

**Comment by forresto** [comment]
The library is not in the graph JSON, rather `editor.$.graph.library = library;` https://github.com/the-grid/the-graph/blob/9c5e6d6715de8a8de897a82f62228fcce286e4b8/the-graph-editor/demo-simple.html#L142

`editor.$.graph` is the polymer `the-graph` instance inside the polymer ``the-graph-editor` instance: https://github.com/the-grid/the-graph/blob/master/the-graph/the-graph.html

All of this should be cleaned up and refactored some day.

**Comment by forresto** [comment]
0. internally the-graph uses a noflo graph as the model and event emitter for graph changes, but it doesn't specify using noflo on the runtime side

1. noflo-ui pulls the-graph in with bower: https://github.com/noflo/noflo-ui/blob/2158cb79a91ea316099c2efc61ce5f72d34a514b/bower.json#L21

**Comment by freder** [comment]
thanks, @forresto!
