### ISSUE TITLE
Port tooltip does not dismiss after mouse leave

### ISSUE THREAD

**Issue by lacek** [the-grid/the-graph#226]
Bug is introduced since 0.3.11. It was fine in 0.3.10.

Steps to reproduce:

1. Pull latest code, build and host locally
    
    ```bash
    git clone https://github.com/the-grid/the-graph
    git checkout tags/0.3.11
    cd the-graph && npm install && grunt build
    python -m SimpleHTTPServer 3000
    ```
2.  visit http://localhost:3000/the-graph-editor
3. Hover a port with the cursor and leave, tooltip remains
    
    ![the-graph-port-tooltip](https://cloud.githubusercontent.com/assets/1272100/10196745/fd13dc0c-67c6-11e5-951a-3b5fda856f3e.gif)
    Tooltip dismissed If scrolled to zoom in or out.

Switch back to 0.3.10, rebuild and test, problem does not occur.

**Comment by lacek** [comment]
Seems to be problem of upgrade react to 0.13.3. Normal at 29efed5, and problem appears at one commit later: ed66aea

**Comment by forresto** [comment]
Thanks for this report. Turned out to be a small bug.
