### ISSUE TITLE
How to customize icons?

### ISSUE THREAD

**Issue by ultraN** [the-grid/the-graph#281]
I want to use my icons instead of AwesomeFontSVG. Where is the function that renders icon in each block?

**Comment by forresto** [comment]
Should be doable if you're replacing it with another SVG icon font. `TheGraph.FONT_AWESOME[ this.props.icon ]` is the unicode character. It's here: https://github.com/the-grid/the-graph/blob/f1d0f8909a2f826e924270a63f6c49cfac4a3099/the-graph/the-graph-node.js#L427-L443
