### ISSUE TITLE
How to set the default zoom multiple?

### ISSUE THREAD

**Issue by ultraN** [the-grid/the-graph#289]
I found how to set the maximum and minimum zoom multiple, but can't find where to set the default multiple when paged loaded.

**Comment by forresto** [comment]
The default is fit: https://github.com/the-grid/the-graph/blob/07a91262d96cfc228537c4bb6ad182810cef0fbf/the-graph/the-graph-app.js#L71 & there isn't currently an override.

**Comment by ultraN** [comment]
Thank you!
