### ISSUE TITLE
How to edit node properties with left-click?

### ISSUE THREAD

**Issue by mghamry** [the-grid/the-graph#308]
In noflo-ui (i.e. http://app.flowhub.io/#example/3c0ffdf17195649a2d57), when you left-click, the properties menu opens. I have something similar to the old data-flow that we're using, where you left-click on the node and have a display panel open to edit/add properties. I want to accomplish the same thing with the-graph, and ultimately integrate it into AngularJs. 

How can I bring up the properties menu to edit?

**Comment by forresto** [comment]
You can see how noflo-ui uses `addMenuAction` here: https://github.com/noflo/noflo-ui/blob/dce1fc2f48355f0399c4913c31ee5131d48b4c70/elements/noflo-context.html#L89

**Comment by mghamry** [comment]
Thank you - I am attempting to integrate what you have in noflo-ui with
what is in "the-graph", but it's not entirely straightforward. Do you have
any advice with regard to integrating into an AngularJS applications (or
any working examples where noflo is working with AngularJS that functions
the way noflo-ui is set up (with the search bar, left, right click
functions, etc))?
